services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.hub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - jupyterhub_data:/srv/jupyterhub
      - /srv/jupyterhub/home:/srv/jupyterhub/home:rw
      - /srv/jupyterhub/opt-packages:/srv/jupyterhub/opt-packages:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jupyterhub-net
    restart: unless-stopped

networks:
  jupyterhub-net:
    name: jupyterhub-net
    driver: bridge

volumes:
  jupyterhub_data:
